/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ApiBuildRouteImport } from './routes/api/build'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiRedeemRouteImport } from './routes/api/redeem'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ChatThreadIdRouteImport } from './routes/chat.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuildRoute = ApiBuildRouteImport.update({
  id: '/api/build',
  path: '/api/build',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRedeemRoute = ApiRedeemRouteImport.update({
  id: '/api/redeem',
  path: '/api/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/chat/$threadId',
  path: '/chat/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/api/build': typeof ApiBuildRoute
  '/api/chat': typeof ApiChatRoute
  '/api/redeem': typeof ApiRedeemRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/api/build': typeof ApiBuildRoute
  '/api/chat': typeof ApiChatRoute
  '/api/redeem': typeof ApiRedeemRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/api/build': typeof ApiBuildRoute
  '/api/chat': typeof ApiChatRoute
  '/api/redeem': typeof ApiRedeemRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pricing'
    | '/api/build'
    | '/api/chat'
    | '/api/redeem'
    | '/api/transcribe'
    | '/chat/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pricing'
    | '/api/build'
    | '/api/chat'
    | '/api/redeem'
    | '/api/transcribe'
    | '/chat/$threadId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/pricing'
    | '/api/build'
    | '/api/chat'
    | '/api/redeem'
    | '/api/transcribe'
    | '/chat/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  PricingRoute: typeof PricingRoute
  ApiBuildRoute: typeof ApiBuildRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiRedeemRoute: typeof ApiRedeemRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ChatThreadIdRoute: typeof ChatThreadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/build': {
      id: '/api/build'
      path: '/api/build'
      fullPath: '/api/build'
      preLoaderRoute: typeof ApiBuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/redeem': {
      id: '/api/redeem'
      path: '/api/redeem'
      fullPath: '/api/redeem'
      preLoaderRoute: typeof ApiRedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$threadId': {
      id: '/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  PricingRoute: PricingRoute,
  ApiBuildRoute: ApiBuildRoute,
  ApiChatRoute: ApiChatRoute,
  ApiRedeemRoute: ApiRedeemRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ChatThreadIdRoute: ChatThreadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
